
--
-- DROP TABLES
--

DROP TABLE film_actor CASCADE CONSTRAINTS;
DROP TABLE film_category CASCADE CONSTRAINTS;
DROP TABLE payment CASCADE CONSTRAINTS;
DROP TABLE rental CASCADE CONSTRAINTS;
DROP TABLE actor CASCADE CONSTRAINTS;
DROP TABLE category CASCADE CONSTRAINTS;
DROP TABLE customer CASCADE CONSTRAINTS;
DROP TABLE inventory CASCADE CONSTRAINTS;
ALTER TABLE staff DROP CONSTRAINT fk_staff_store;
DROP TABLE store CASCADE CONSTRAINTS;
DROP TABLE staff CASCADE CONSTRAINTS;
DROP TABLE address CASCADE CONSTRAINTS;
DROP TABLE city CASCADE CONSTRAINTS;
DROP TABLE country CASCADE CONSTRAINTS;
DROP TABLE film CASCADE CONSTRAINTS;
DROP TABLE language CASCADE CONSTRAINTS;



--
-- DROP VIEWS
--

DROP VIEW customer_list;
DROP VIEW film_list;
DROP VIEW sales_by_film_category;
DROP VIEW sales_by_store;
DROP VIEW staff_list;