CREATE OR REPLACE VIEW premium_customer AS
SELECT c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, COUNT(r.RENTAL_ID) AS numFilms
FROM NEW_CUSTOMER c
INNER JOIN NEW_RENTAL r
    ON c.CUSTOMER_ID = r.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME
HAVING COUNT(r.RENTAL_ID) > 30;