-- Sakila in DEMO30 Benutzer laden 

-- GRANTS durchführen
GRANT SELECT ON ACTOR TO PUBLIC;
GRANT SELECT ON COUNTRY TO PUBLIC;
GRANT SELECT ON CITY TO PUBLIC;
GRANT SELECT ON ADDRESS TO PUBLIC;
GRANT SELECT ON CATEGORY TO PUBLIC;
GRANT SELECT ON STAFF TO PUBLIC;
GRANT SELECT ON STORE TO PUBLIC;
GRANT SELECT ON CUSTOMER TO PUBLIC;
GRANT SELECT ON LANGUAGE TO PUBLIC;
GRANT SELECT ON FILM TO PUBLIC;
GRANT SELECT ON FILM_ACTOR TO PUBLIC;
GRANT SELECT ON FILM_CATEGORY TO PUBLIC;
GRANT SELECT ON INVENTORY TO PUBLIC;
GRANT SELECT ON RENTAL TO PUBLIC;
GRANT SELECT ON PAYMENT TO PUBLIC;


