-- 1a
SELECT e.EMPLOYEE_ID, e.LAST_NAME, e.HIRE_DATE, e.SALARY
FROM EMPLOYEES m
INNER JOIN EMPLOYEES e
    ON e.MANAGER_ID = m.EMPLOYEE_ID
WHERE m.EMPLOYEE_ID = 205;

-- 1b(unter => ohne 205)
SELECT EMPLOYEE_ID, LAST_NAME, HIRE_DATE, SALARY
FROM (SELECT EMPLOYEE_ID, LAST_NAME, HIRE_DATE, SALARY
FROM EMPLOYEES
START WITH EMPLOYEE_ID = 205
CONNECT BY NOCYCLE PRIOR EMPLOYEE_ID = MANAGER_ID)
WHERE EMPLOYEE_ID != 205;

-- 2
SELECT EMPLOYEE_ID, MANAGER_ID, LAST_NAME, Level
FROM EMPLOYEES
WHERE Level = 3
START WITH EMPLOYEE_ID = 102
CONNECT BY NOCYCLE PRIOR EMPLOYEE_ID = MANAGER_ID;

-- 3
SELECT LPAD(LAST_NAME, LENGTH(LAST_NAME) + LEVEL - 1, '_') AS LAST_NAME,
    EMPLOYEE_ID,
    MANAGER_ID,
    LEVEL AS Hierarchy_Level
FROM EMPLOYEES
START WITH EMPLOYEE_ID = 100
CONNECT BY NOCYCLE PRIOR EMPLOYEE_ID = MANAGER_ID;