-- 1
SELECT f.TITLE,
    f.LENGTH,
    LISTAGG(
            CASE
                WHEN a.ACTOR_ID IS NULL THEN
                    'no actors'
                ELSE
                    LPAD(a.FIRST_NAME, 1) || '.' || a.LAST_NAME END, ', ')
            WITHIN GROUP ( ORDER BY a.LAST_NAME )
FROM FILM f
LEFT JOIN FILM_ACTOR fa
    ON f.FILM_ID = fa.FILM_ID
LEFT JOIN ACTOR a
    ON fa.ACTOR_ID = a.ACTOR_ID
WHERE f.RELEASE_YEAR = 1991
GROUP BY f.TITLE, f.LENGTH
ORDER BY f.LENGTH DESC;

-- 2
SELECT c.FIRST_NAME || ' ' || c.LAST_NAME AS customer,
    LISTAGG(f.TITLE || ' (' || f.RELEASE_YEAR || ')', ', ')
            WITHIN GROUP ( ORDER BY f.RELEASE_YEAR DESC) AS films
FROM CUSTOMER c
INNER JOIN STORE s
    ON c.STORE_ID = s.STORE_ID
INNER JOIN RENTAL r
    ON c.CUSTOMER_ID = r.CUSTOMER_ID
INNER JOIN INVENTORY i
    ON r.INVENTORY_ID = i.INVENTORY_ID
INNER JOIN FILM f
    ON i.FILM_ID = f.FILM_ID
WHERE s.STORE_ID = 4
GROUP BY c.FIRST_NAME, c.LAST_NAME
ORDER BY LAST_NAME;