-- rollup
SELECT c.NAME, f.RATING, COUNT(*), SUM(f.LENGTH)
FROM FILM f
INNER JOIN FILM_CATEGORY fc
    ON f.FILM_ID = fc.FILM_ID
INNER JOIN CATEGORY c
    ON fc.CATEGORY_ID = c.CATEGORY_ID
WHERE c.NAME IN ('Comedy', 'Music')
GROUP BY ROLLUP (c.NAME, f.RATING);

-- grouping set
SELECT c.NAME, f.RATING, COUNT(*), SUM(f.LENGTH)
FROM FILM f
INNER JOIN FILM_CATEGORY fc
    ON f.FILM_ID = fc.FILM_ID
INNER JOIN CATEGORY c
    ON fc.CATEGORY_ID = c.CATEGORY_ID
WHERE c.NAME IN ('Comedy', 'Music')
GROUP BY GROUPING SETS ((c.NAME, f.RATING), c.NAME, ());

-- manuell
SELECT c.NAME, f.RATING, COUNT(*), SUM(f.LENGTH)
FROM FILM f
INNER JOIN FILM_CATEGORY fc
    ON f.FILM_ID = fc.FILM_ID
INNER JOIN CATEGORY c
    ON fc.CATEGORY_ID = c.CATEGORY_ID
WHERE c.NAME IN ('Comedy', 'Music')
GROUP BY c.NAME, f.RATING
UNION ALL
SELECT c.NAME, NULL, COUNT(*), SUM(f.LENGTH)
FROM FILM f
INNER JOIN FILM_CATEGORY fc
    ON f.FILM_ID = fc.FILM_ID
INNER JOIN CATEGORY c
    ON fc.CATEGORY_ID = c.CATEGORY_ID
WHERE c.NAME IN ('Comedy', 'Music')
GROUP BY c.NAME
UNION ALL
SELECT NULL, NULL, COUNT(*), SUM(f.LENGTH)
FROM FILM f
INNER JOIN FILM_CATEGORY fc
    ON f.FILM_ID = fc.FILM_ID
INNER JOIN CATEGORY c
    ON fc.CATEGORY_ID = c.CATEGORY_ID
WHERE c.NAME IN ('Comedy', 'Music');